### ISSUE TITLE
error=2, No such file or directory 

### ISSUE THREAD

**Issue by oyeyemi** [easy-global-market/nifi-file-identity-provider-bundle#33]
I was trying to build the nar from your source but i received the following error.

Platform: **Ubuntu 22.04**(VirtualBox)
Jdk: OpenJDK Runtime Environment (build **17.0.9**+9-Ubuntu-122.04)
Build tools: command line.

![id_prov_err1](https://github.com/easy-global-market/nifi-file-identity-provider-bundle/assets/7483333/def969a7-03c2-4ae7-b891-119507aa9276)

Thank you.

**Comment by bobeal** [comment]
hi @oyeyemi,

Looking at the error message, seems like you don't have the Java compiler installed on your computer (`Cannot run program javac`).

What do you get if you run this command: `javac --version`?

**Comment by bobeal** [comment]
Just spotted the warning at the beginning: `unable to autodetect 'javac' path using 'javac' from the environment`

It may come from the `JAVA_HOME` environment variable no set. Also saw this https://intellij-support.jetbrains.com/hc/en-us/community/posts/7656471014290-Unable-to-autodetect-javac-path-using-javac-from-the-environment that may worth the try.

**Comment by oyeyemi** [comment]
> Just spotted the warning at the beginning: `unable to autodetect 'javac' path using 'javac' from the environment`
> 
> It may come from the `JAVA_HOME` environment variable no set. Also saw this https://intellij-support.jetbrains.com/hc/en-us/community/posts/7656471014290-Unable-to-autodetect-javac-path-using-javac-from-the-environment that may worth the try.

Thank you sir. That is exactly what happened. Javac was missing. I have fixed it by installing the compiler as you stated.
Thank you sir.
