### ISSUE TITLE
Unable to locate initial admin admin to seed policies

### ISSUE THREAD

**Issue by oyeyemi** [easy-global-market/nifi-file-identity-provider-bundle#34]
After the necessary configurations following your procedure, Nifi server started but did not bring login page & complained their is set policies. Then i edited the **authorizers.xml** file as follows.
    
    `    <accessPolicyProvider>
        <identifier>file-access-policy-provider</identifier>
        <class>org.apache.nifi.authorization.FileAccessPolicyProvider</class>
        <property name="User Group Provider">file-user-group-provider</property>
        <property name="Authorizations File">./conf/authorizations.xml</property>
        <property name="Initial Admin Identity">admin</property>
        <property name="Legacy Authorized Users File"></property>
        <property name="Node Identity 1">localhost</property>
        <property name="Node Group"></property>
    </accessPolicyProvider>`
    
    **ERROR:**
    
    
    `Caused by: org.apache.nifi.authorization.exception.AuthorizerCreationException: org.apache.nifi.authorization.exception.AuthorizerCreationException: Unable to locate initial admin admin to seed policies
	at org.apache.nifi.authorization.FileAccessPolicyProvider.onConfigured(FileAccessPolicyProvider.java:267)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.nifi.authorization.AccessPolicyProviderInvocationHandler.invoke(AccessPolicyProviderInvocationHandler.java:54)
	at jdk.proxy3/jdk.proxy3.$Proxy50.onConfigured(Unknown Source)
	at org.apache.nifi.authorization.AuthorizerFactoryBean.loadProviderProperties(AuthorizerFactoryBean.java:211)
	at org.apache.nifi.authorization.AuthorizerFactoryBean.getObject(AuthorizerFactoryBean.java:168)
	at org.apache.nifi.authorization.AuthorizerFactoryBean.getObject(AuthorizerFactoryBean.java:72)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)`
    
    NOTE: THIS IS A FRESH INSTALLATION. I DID NOT START NIFI AT UNTIL AFTER CONFIGUATION
    **Attached is my nifi-app.log file**
    Thank you sir.
    
    
[nifi-app.log](https://github.com/easy-global-market/nifi-file-identity-provider-bundle/files/13801608/nifi-app.log)

**Comment by oyeyemi** [comment]
> ```
> After the necessary configurations following your procedure, Nifi server started but did not bring login page & complained their is set policies. Then i edited the **authorizers.xml** file as follows.
> 
> `    <accessPolicyProvider>
>     <identifier>file-access-policy-provider</identifier>
>     <class>org.apache.nifi.authorization.FileAccessPolicyProvider</class>
>     <property name="User Group Provider">file-user-group-provider</property>
>     <property name="Authorizations File">./conf/authorizations.xml</property>
>     <property name="Initial Admin Identity">admin</property>
>     <property name="Legacy Authorized Users File"></property>
>     <property name="Node Identity 1">localhost</property>
>     <property name="Node Group"></property>
> </accessPolicyProvider>`
> 
> **ERROR:**
> 
> 
> `Caused by: org.apache.nifi.authorization.exception.AuthorizerCreationException: org.apache.nifi.authorization.exception.AuthorizerCreationException: Unable to locate initial admin admin to seed policies
> at org.apache.nifi.authorization.FileAccessPolicyProvider.onConfigured(FileAccessPolicyProvider.java:267)
> at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
> at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> at org.apache.nifi.authorization.AccessPolicyProviderInvocationHandler.invoke(AccessPolicyProviderInvocationHandler.java:54)
> at jdk.proxy3/jdk.proxy3.$Proxy50.onConfigured(Unknown Source)
> at org.apache.nifi.authorization.AuthorizerFactoryBean.loadProviderProperties(AuthorizerFactoryBean.java:211)
> at org.apache.nifi.authorization.AuthorizerFactoryBean.getObject(AuthorizerFactoryBean.java:168)
> at org.apache.nifi.authorization.AuthorizerFactoryBean.getObject(AuthorizerFactoryBean.java:72)
> at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)`
> 
> NOTE: THIS IS A FRESH INSTALLATION. I DID NOT START NIFI AT UNTIL AFTER CONFIGUATION
> **Attached is my nifi-app.log file**
> Thank you sir.
> ```
> 
> [nifi-app.log](https://github.com/easy-global-market/nifi-file-identity-provider-bundle/files/13801608/nifi-app.log)

Thanks.
I have figured it out. I missed a config inside the authorizers.xml,

**Comment by bobeal** [comment]
Good to hear. Let me know if you have any other problem running the extension. Closing this issue.
